package pe.com.app.common;

public interface ConstantMessage {
	String SAVE = "SE GUARDO CORRECTAMENTE";
	String UPDATE = "SE MODIFICO CORRECTAMENTE";
	String DELETE = "SE ELIMINO CORRECTAMENTE";
	String SELECTED_ROW = "SELECCIONE UN REGISTRO";
	String SELECTED_KARDEX = "SELECCIONE UN KARDEX";
	String PERSONA_NOT_FOUNDED = "NO EXISTE INFORMACION PARA LA PERSONA";
	String SELECTED_PARTICIPANTE = "SELECCIONE UN PARTICIPANTE";
	String SELECTED_SERVICIO = "SELECCIONE UN SERVICIO";
	String INPUT_DATA_FIRMA= "DEBE REGISTAR ALMENOS UNA FIRMA";
	String INPUT_KARDEX= "INGRESE EL NUMERO DE KARDEX";
	String USUARIO_NO_SESSION = "LA SESION DEL USUARIO HA CADUCADO";
	String INGRESE_RUC = "INGRESE RUC";
	String DUPLICADO_RUC = "EXISTE MAS DE UN EMPRESA CON EL MISMO NUMERO DE RUC";
	String SINCRONIZADO_OK = "SE CARGO LOS DATOS DE FORMA CORRECTA";
	String INPUT_NOMBRE_PERSONA = "INGRESE EL NOMBRE DE UNA PERSONA";
	String APROBAR_VEHICULAR = "SE APROBO CORRECTAMENTE EL TRAMITE";
	String NO_IMPRESORA = "NO SE ENCONTRO LA IMPRESORA";
	String IMPRIMIR = "SE IMPRIMIO CORRECTAMENTE";
	String INGRESE_PLACA= "INGRESE PLACA";
	String NO_CORRELATIVO= "NO SE PUEDE GENERAR CORRELATIVO PARA EL DOCUMENTO";
}
